##Iris Dataset Classification

In [ ]:
## importing pandas
import sklearn
import numpy
import pandas as pd
from sklearn import datasets

## Problem Understanding
- choose the correct flowers

## Data Understanding

In [ ]:
# dataset in sklearn
iris = datasets.load_iris()

In [ ]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [ ]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
iris_data = pd.DataFrame(iris.data,columns=iris.feature_names);

In [ ]:
iris_data['lable'] = iris.target;

In [ ]:
iris_data

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     lable  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

## 3. Data Preprocessing

In [ ]:
iris_data.dropna(axis=0,inplace=True)

In [ ]:
X = iris_data.iloc[:,0:-1]; ##features
Y = iris_data.iloc[:,-1]; ## labels

In [ ]:
X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,random_state=5);

In [ ]:
X_train

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
39                 5.1               3.4                1.5               0.2
53                 5.5               2.3                4.0               1.3
79                 5.7               2.6                3.5               1.0
10                 5.4               3.7                1.5               0.2
50                 7.0               3.2                4.7               1.4
..                 ...               ...                ...               ...
8                  4.4               2.9                1.4               0.2
73                 6.1               2.8                4.7               1.2
144                6.7               3.3                5.7               2.5
118                7.7               2.6                6.9               2.3
99                 5.7               2.8                4.1               1.3

[120 rows x 4 columns]

In [ ]:
Y_train

39     0
53     1
79     1
10     0
50     1
      ..
8      0
73     1
144    2
118    2
99     1
Name: lable, Length: 120, dtype: int64

## Modelling

In [ ]:
from sklearn import tree

model = tree.DecisionTreeClassifier()
model.fit(X_train,Y_train);

In [ ]:
model

DecisionTreeClassifier()

## 5. Evaluation

In [ ]:
y_predict = model.predict(X_test)

In [ ]:
y_predict

array([1, 2, 2, 0, 2, 2, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 2, 2, 0, 0, 1, 2,
       0, 1, 1, 2, 1, 1, 1, 2])

In [ ]:
# Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix;
print(confusion_matrix(Y_test,y_predict))

[[ 8  0  0]
 [ 0  9  2]
 [ 0  1 10]]


In [ ]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
print('Accuracy Score',accuracy_score(Y_test, y_predict)*100,'%')
print('Precision Macro Score',precision_score(Y_test, y_predict,average = 'macro')*100,'%')
print('Recall_Score',recall_score(Y_test, y_predict, average = 'macro')*100,'%')
print('F_Score',f1_score(Y_test, y_predict, average = 'macro')*100,'%')

Accuracy Score 90.0 %
Precision Macro Score 91.11111111111111 %
Recall_Score 90.90909090909092 %
F_Score 90.89026915113871 %
